cc_library (
        name = 'kafka_client',
        srcs = glob(['*.cpp']),
        deps = [           
            '//common:common',
            '//thirdparty/rdkafka:rdkafka', 
            '//thirdparty/glog:glog',            
        ]
)
