cc_library(
        name = 'timer',
        srcs = glob([
            '*.cpp',
        ]),
        deps = [
            '//context:context',
            '//common:common',
            '//config:config',
            '//frame:frame',
            '//model_manager:model_manager',
        ],
)
